version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - 8080:80
    volumes:
      - ${SSD_DIR}:/srv
    restart: unless-stopped
